modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="corazondemelon"
version="1.0.0"
displayName="Corazón de Melon"
description='''
Encuentra corazones mágicos, sube tu nivel de Inocencia (de Bruto a Santo) y haz que los mobs te traten con cariño.
Conoce a Mao, un pequeño ángel que puede ser tu compañero y asistente personal con IA.
'''

[[dependencies.corazondemelon]]
modId="forge"
mandatory=true
versionRange="[47.3.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.corazondemelon]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
